# Generated by Django 2.2.7 on 2019-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191121_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='Post meta description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Post meta keywords'),
        ),
    ]
