# Generated by Django 2.2.7 on 2019-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191127_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp'], 'verbose_name': 'blog article', 'verbose_name_plural': 'blog articles'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='Post meta description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Post meta keywords'),
        ),
    ]
