# Generated by Django 2.2.7 on 2019-11-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191127_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp'], 'verbose_name': 'BlogPost', 'verbose_name_plural': 'BlogPosts'},
        ),
    ]
