# Generated by Django 2.2.5 on 2019-09-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
