# Generated by Django 2.2.5 on 2019-09-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190913_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='language',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='style',
        ),
    ]
